blank_issues_enabled: false
contact_links:
  - name: Discussion Forum
    url: https://github.com/jer/agentic-best-practices/discussions
    about: For questions and general discussions about agentic best practices
